spring:
  application:
    name: traffic-local

  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/ipse
    username: seungbinyang
    password: fds

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true
        show_sql: true

    defer-datasource-initialization: true

  openapi:
    subway:
      apiKey: ENC(ZHhyrqpYzuxZ09onTfn+eIboFAcR6JMQZG5l8kPnTGXeli0io2uSgEbXkUgGKQn8)
      url:
        arrivalInfo: http://swopenAPI.seoul.go.kr/api/subway/%s/json/realtimeStationArrival/%s/%s/%s

  sql:
    init:
      mode: always


